language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
  - sudo apt-get install clamav -y
  - sudo apt-get install clamav-daemon -y
  - /usr/bin/clamdscan --fdpass composer.json
  - composer install --dev

script: ./bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
